name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '10.0.x'

      - name: Install dependencies
        run: dotnet restore MythosSoftware.FastMap\MythosSoftware.FastMap.csproj

      - name: Build
        run: dotnet build MythosSoftware.FastMap\MythosSoftware.FastMap.csproj --configuration Release

      - name: Clean package output
        run: rm -rf out

      - name: Build solution and generate NuGet package
        run: |
          BASE_VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" MythosSoftware.FastMap\MythosSoftware.FastMap.csproj)
          VERSION_PREFIX=$(echo "$BASE_VERSION" | cut -d. -f1,2)
          PACKAGE_VERSION="$VERSION_PREFIX.${{ github.run_number }}"

          echo "Packing version: $PACKAGE_VERSION"
          dotnet pack MythosSoftware.FastMap\MythosSoftware.FastMap.csproj -c Release -o out -p:PackageVersion=$PACKAGE_VERSION 

      - name: Display folder
        run: ls out/ && stat out/*

      - name: Publish
        run: dotnet nuget push out/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}